/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Livro;
import controle.ControleLivro;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class ViewListaLivros extends javax.swing.JDialog {
    
    ControleLivro controle = null;
    ArrayList<Livro> lista = null;

    /**
     * Creates new form ViewListaLivros
     */
    public ViewListaLivros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        jTextFieldQtdeRegistros.requestFocus();
        jButtonPesquisarLivro.setEnabled(false);
        
         try {
            controle = new ControleLivro("livro.txt");
            lista = new ArrayList<>(controle.recuperar());
            jTextFieldQtdeRegistros.setText(""+lista.size());

            imprimirDadosDoLivroEmLista(controle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }
    
     private void imprimirDadosDoLivroEmLista(ArrayList<Livro> listaDeLivros) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableListaLivros.getModel();
        model.setNumRows(0);
        Collections.sort(listaDeLivros);
        for (int pos = 0; pos < listaDeLivros.size(); pos++) {
            String[] linha = new String[9];
            Livro aux = listaDeLivros.get(pos);
            linha[0] = " " + aux.getId();
            linha[1] = aux.getIsbn();
            linha[2] = aux.getTituloLivro().toUpperCase();
            linha[3] = aux.getSubTituloLivro().toUpperCase();
            linha[4] = aux.getAutor().getNomeAutor().toUpperCase();
            linha[5] = aux.getEditora().getDescricaoEditora().toUpperCase();
            linha[6] = aux.getArea().getCdd() + "-" + aux.getArea().getDescricaoDaArea().toUpperCase();
            linha[7] = aux.getEdicao();
            linha[8] = "" + aux.getAnoDePublicacao();
            model.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaLivros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaLivros = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQtdeRegistros = new javax.swing.JTextField();
        jTextFieldDigitarDados = new javax.swing.JTextField();
        jButtonPesquisarLivro = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de livros");

        jTableListaLivros.setAutoCreateRowSorter(true);
        jTableListaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ISBN", "TÍTULO", "SUB-TÍTULO", "AUTOR", "EDITORA", "ÁREA", "EDIÇÃO", "ANO PUBLIC."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaLivrosMouseClicked(evt);
            }
        });
        jTableListaLivros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableListaLivrosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaLivros);
        if (jTableListaLivros.getColumnModel().getColumnCount() > 0) {
            jTableListaLivros.getColumnModel().getColumn(0).setMinWidth(50);
            jTableListaLivros.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableListaLivros.getColumnModel().getColumn(1).setMinWidth(120);
            jTableListaLivros.getColumnModel().getColumn(1).setMaxWidth(120);
            jTableListaLivros.getColumnModel().getColumn(7).setMinWidth(60);
            jTableListaLivros.getColumnModel().getColumn(7).setMaxWidth(60);
            jTableListaLivros.getColumnModel().getColumn(8).setMinWidth(60);
            jTableListaLivros.getColumnModel().getColumn(8).setMaxWidth(60);
        }

        jButtonFechar.setText("FECHAR");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButton1.setText("IMPRIMIR");

        jLabel2.setText("Quant. de Registros:");

        jTextFieldQtdeRegistros.setEditable(false);

        jTextFieldDigitarDados.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDigitarDados.setText("Digite aqui o ISBN ou título do livro ou autor do livro");
        jTextFieldDigitarDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDigitarDadosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDigitarDadosFocusLost(evt);
            }
        });

        jButtonPesquisarLivro.setText("Pesquisar");
        jButtonPesquisarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarLivroActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaLivrosLayout = new javax.swing.GroupLayout(jPanelListaLivros);
        jPanelListaLivros.setLayout(jPanelListaLivrosLayout);
        jPanelListaLivrosLayout.setHorizontalGroup(
            jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaLivrosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar))
                    .addGroup(jPanelListaLivrosLayout.createSequentialGroup()
                        .addComponent(jTextFieldDigitarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarLivro)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelListaLivrosLayout.setVerticalGroup(
            jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaLivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDigitarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanelListaLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaLivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableListaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaLivrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableListaLivrosMouseClicked

    private void jTableListaLivrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaLivrosKeyReleased

    }//GEN-LAST:event_jTableListaLivrosKeyReleased

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonPesquisarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarLivroActionPerformed
        try {
            imprimirDadosDoLivroEmLista(controle.pesquisar(jTextFieldDigitarDados.getText()));
            jTextFieldDigitarDados.requestFocus();
            jTextFieldDigitarDados.setText("");
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
            jTextFieldDigitarDados.requestFocus();
            jTextFieldDigitarDados.setText("");
        }
    }//GEN-LAST:event_jButtonPesquisarLivroActionPerformed

    private void jTextFieldDigitarDadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDigitarDadosFocusGained
        if (jTextFieldDigitarDados.getText().equals("Digite aqui o ISBN ou título do livro ou autor do livro")) {
            jTextFieldDigitarDados.setText("");
            jButtonPesquisarLivro.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldDigitarDadosFocusGained

    private void jTextFieldDigitarDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDigitarDadosFocusLost
         if (jTextFieldDigitarDados.getText().equals("")) {
            jTextFieldDigitarDados.setText("Digite aqui o ISBN ou título do livro ou autor do livro");
            jButtonPesquisarLivro.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldDigitarDadosFocusLost

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        try {
            imprimirDadosDoLivroEmLista(controle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewListaLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewListaLivros dialog = new ViewListaLivros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisarLivro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelListaLivros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaLivros;
    private javax.swing.JTextField jTextFieldDigitarDados;
    private javax.swing.JTextField jTextFieldQtdeRegistros;
    // End of variables declaration//GEN-END:variables
}
