/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Exemplar;
import controle.ControleExemplar;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class ViewListaExemplares extends javax.swing.JDialog {

    ControleExemplar controle = null;
    ArrayList<Exemplar> lista = null;

    /**
     * Creates new form ViewListaExemplares
     */
    public ViewListaExemplares(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        jButtonPesquisarExemplares.setEnabled(false);
        jTextFieldQtdeDeRegistros.requestFocus();

        controle = new ControleExemplar("Exemplar.txt");
        lista = new ArrayList<Exemplar>(controle.recuperar());
        jTextFieldQtdeDeRegistros.setText("" + lista.size());
        imprimirListaDeExemplares(controle.recuperar());

    }

    private void imprimirListaDeExemplares(ArrayList<Exemplar> listaDeExemplares) throws Exception {
        try {
            DefaultTableModel model = (DefaultTableModel) jTableListaDeExemplares.getModel();
            model.setNumRows(0);
            Collections.sort(listaDeExemplares);

            for (int pos = 0; pos < listaDeExemplares.size(); pos++) {
                String[] linha = new String[14];
                Exemplar aux = listaDeExemplares.get(pos);
                linha[0] = "" + aux.getId();
                linha[1] = aux.getLivro().getIsbn();
                linha[2] = aux.getLivro().getTituloLivro().toUpperCase();
                linha[3] = aux.getLivro().getSubTituloLivro().toUpperCase();
                linha[4] = aux.getLivro().getAutor().getNomeAutor().toUpperCase();
                linha[5] = aux.getLivro().getEditora().getDescricaoEditora().toUpperCase();
                linha[6] = aux.getLivro().getArea().getDescricaoDaArea().toUpperCase();
                linha[7] = "" + aux.getLivro().getAnoDePublicacao();
                linha[8] = aux.getLivro().getEdicao().toUpperCase();
                linha[9] = new SimpleDateFormat("dd/MM/yyyy").format(aux.getDataAquisicao());
                linha[10] = String.format("%.2f", aux.getPrecoExemplar());
                linha[11] = aux.getSituacao().toString();
                linha[12] = aux.getDisponibilidade().toString();
                linha[13] = aux.getMotivoInativacao().toUpperCase();
                model.addRow(linha);

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaDeExemplares = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaDeExemplares = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQtdeDeRegistros = new javax.swing.JTextField();
        jTextField1DigitarDados = new javax.swing.JTextField();
        jButtonPesquisarExemplares = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Exemplares");

        jTableListaDeExemplares.setAutoCreateRowSorter(true);
        jTableListaDeExemplares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Ex.", "ISBN", "Título do Livro", "Sub-Título", "Autor(a)", "Editora", "Área", "Edição", "Ano Public.", "Data Aquisição", "Preço R$", "Situação", "Disponibilidade", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaDeExemplares);
        if (jTableListaDeExemplares.getColumnModel().getColumnCount() > 0) {
            jTableListaDeExemplares.getColumnModel().getColumn(0).setMinWidth(50);
            jTableListaDeExemplares.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableListaDeExemplares.getColumnModel().getColumn(1).setMinWidth(120);
            jTableListaDeExemplares.getColumnModel().getColumn(1).setMaxWidth(120);
            jTableListaDeExemplares.getColumnModel().getColumn(2).setMinWidth(180);
            jTableListaDeExemplares.getColumnModel().getColumn(2).setMaxWidth(180);
            jTableListaDeExemplares.getColumnModel().getColumn(3).setMinWidth(180);
            jTableListaDeExemplares.getColumnModel().getColumn(8).setMinWidth(50);
            jTableListaDeExemplares.getColumnModel().getColumn(8).setMaxWidth(50);
            jTableListaDeExemplares.getColumnModel().getColumn(9).setMinWidth(80);
            jTableListaDeExemplares.getColumnModel().getColumn(9).setMaxWidth(80);
            jTableListaDeExemplares.getColumnModel().getColumn(10).setMinWidth(60);
            jTableListaDeExemplares.getColumnModel().getColumn(10).setMaxWidth(60);
            jTableListaDeExemplares.getColumnModel().getColumn(11).setMinWidth(70);
            jTableListaDeExemplares.getColumnModel().getColumn(11).setMaxWidth(70);
            jTableListaDeExemplares.getColumnModel().getColumn(12).setMinWidth(100);
            jTableListaDeExemplares.getColumnModel().getColumn(12).setMaxWidth(100);
        }

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonImprimir.setText("Imprimir");

        jLabel2.setText("Quant. de Registros:");

        jTextField1DigitarDados.setForeground(new java.awt.Color(102, 102, 102));
        jTextField1DigitarDados.setText("Digite aqui o título do livro para pesquisar");
        jTextField1DigitarDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1DigitarDadosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1DigitarDadosFocusLost(evt);
            }
        });

        jButtonPesquisarExemplares.setText("Pesquisar");
        jButtonPesquisarExemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarExemplaresActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaDeExemplaresLayout = new javax.swing.GroupLayout(jPanelListaDeExemplares);
        jPanelListaDeExemplares.setLayout(jPanelListaDeExemplaresLayout);
        jPanelListaDeExemplaresLayout.setHorizontalGroup(
            jPanelListaDeExemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaDeExemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaDeExemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1333, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaDeExemplaresLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdeDeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFechar))
                    .addGroup(jPanelListaDeExemplaresLayout.createSequentialGroup()
                        .addComponent(jTextField1DigitarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarExemplares)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelListaDeExemplaresLayout.setVerticalGroup(
            jPanelListaDeExemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaDeExemplaresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaDeExemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1DigitarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarExemplares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelListaDeExemplaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButtonImprimir)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQtdeDeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaDeExemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaDeExemplares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonPesquisarExemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarExemplaresActionPerformed
        try {
            imprimirListaDeExemplares(controle.pesquisarExemplar(jTextField1DigitarDados.getText()));
            jTextField1DigitarDados.requestFocus();
            jTextField1DigitarDados.setText("");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
            jTextField1DigitarDados.requestFocus();
            jTextField1DigitarDados.setText("");
        }
    }//GEN-LAST:event_jButtonPesquisarExemplaresActionPerformed

    private void jTextField1DigitarDadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1DigitarDadosFocusGained
        if (jTextField1DigitarDados.getText().equals("Digite aqui o título do livro para pesquisar")) {
            jTextField1DigitarDados.setText("");
            jButtonPesquisarExemplares.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField1DigitarDadosFocusGained

    private void jTextField1DigitarDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1DigitarDadosFocusLost
        if (jTextField1DigitarDados.getText().equals("")) {
            jTextField1DigitarDados.setText("Digite aqui o título do livro para pesquisar");
            jButtonPesquisarExemplares.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField1DigitarDadosFocusLost

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        try {
            imprimirListaDeExemplares(controle.recuperar());
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewListaExemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewListaExemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewListaExemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewListaExemplares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    ViewListaExemplares dialog = new ViewListaExemplares(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ViewListaExemplares.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisarExemplares;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelListaDeExemplares;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaDeExemplares;
    private javax.swing.JTextField jTextField1DigitarDados;
    private javax.swing.JTextField jTextFieldQtdeDeRegistros;
    // End of variables declaration//GEN-END:variables
}
