/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.AreaCdd;
import controle.ControleArea;
import java.awt.geom.Area;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class ViewListaAreas extends javax.swing.JDialog {
    
    ControleArea controle;
    ArrayList<AreaCdd> lista = null;

    /**
     * Creates new form TelaListaAreas
     */
    public ViewListaAreas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         this.setLocationRelativeTo(parent);
            parent.setVisible(true);
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
         jButtonPesquisarArea.setEnabled(false);
         jTextFieldQtdeRegistros.requestFocus();
        
        try{
        controle = new ControleArea("areaCdd.txt");
        imprimirDadosAreaGrid(controle.recuperar());
        lista = new ArrayList<>(controle.recuperar());
        jTextFieldQtdeRegistros.setText(""+lista.size());
        }
        catch(Exception erro){
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }
    
     private void imprimirDadosAreaGrid(ArrayList<AreaCdd> lista) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableListaDeAreas.getModel();
        model.setNumRows(0);
        Collections.sort(lista);
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[3];
            AreaCdd aux = lista.get(pos);
            linha[0] = "" + aux.getId();
            linha[1] = aux.getCdd();
            linha[2] = aux.getDescricaoDaArea().toUpperCase();
            model.addRow(linha);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaDeAreas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQtdeRegistros = new javax.swing.JTextField();
        jTextFieldDigitarDados = new javax.swing.JTextField();
        jButtonPesquisarArea = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Áreas de Conhecimento do Livro (CDD)");

        jTableListaDeAreas.setAutoCreateRowSorter(true);
        jTableListaDeAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CDD", "ÁREA DE CONHECIMENTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaDeAreas);
        if (jTableListaDeAreas.getColumnModel().getColumnCount() > 0) {
            jTableListaDeAreas.getColumnModel().getColumn(0).setMinWidth(50);
            jTableListaDeAreas.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableListaDeAreas.getColumnModel().getColumn(1).setMinWidth(60);
            jTableListaDeAreas.getColumnModel().getColumn(1).setMaxWidth(60);
        }

        jButton1.setText("IMPRIMIR");

        jButtonFechar.setText("FECHAR");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel2.setText("Quant. de Registros:");

        jTextFieldQtdeRegistros.setEditable(false);

        jTextFieldDigitarDados.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDigitarDados.setText("Digite aqui o código CDD ou a descrição da área do livro");
        jTextFieldDigitarDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDigitarDadosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDigitarDadosFocusLost(evt);
            }
        });

        jButtonPesquisarArea.setText("PESQUISAR");
        jButtonPesquisarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarAreaActionPerformed(evt);
            }
        });

        jButton2.setText("LIMPAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFechar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldDigitarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarArea)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDigitarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        try {

            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonPesquisarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarAreaActionPerformed
        try {
            imprimirDadosAreaGrid(controle.pesquisar(jTextFieldDigitarDados.getText()));
            jTextFieldDigitarDados.requestFocus();
            jTextFieldDigitarDados.setText("");
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonPesquisarAreaActionPerformed

    private void jTextFieldDigitarDadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDigitarDadosFocusGained
            jButtonPesquisarArea.setEnabled(true);
        if (jTextFieldDigitarDados.getText().equals("Digite aqui o código CDD ou a descrição da área do livro")) {
            jTextFieldDigitarDados.setText("");
        }
    }//GEN-LAST:event_jTextFieldDigitarDadosFocusGained

    private void jTextFieldDigitarDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDigitarDadosFocusLost
        if (jTextFieldDigitarDados.getText().equals("")) {
            jTextFieldDigitarDados.setText("Digite aqui o código CDD ou a descrição da área do livro");
            jButtonPesquisarArea.setEnabled(false);
                    
        }
    }//GEN-LAST:event_jTextFieldDigitarDadosFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            imprimirDadosAreaGrid(controle.recuperar());
         
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewListaAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewListaAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewListaAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewListaAreas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewListaAreas dialog = new ViewListaAreas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonPesquisarArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaDeAreas;
    private javax.swing.JTextField jTextFieldDigitarDados;
    private javax.swing.JTextField jTextFieldQtdeRegistros;
    // End of variables declaration//GEN-END:variables
}
