/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Usuario;
import controle.ControleUsuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class ViewListaUsuarios extends javax.swing.JDialog {
    
    ControleUsuario controle = null;
    ArrayList<Usuario> lista = null;
    

    /**
     * Creates new form ViewListaUsuarios
     */
    public ViewListaUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            
            controle = new ControleUsuario("Usuarios.txt");
            lista = new ArrayList<Usuario>(controle.recuperar());
            jTextFieldQtdeRegistros.setText(lista.size() + "");
            imprimirDadosDoUsuarioNaTabela(lista);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }
    
    private void imprimirDadosDoUsuarioNaTabela(ArrayList<Usuario> lista) throws Exception {

        DefaultTableModel model = (DefaultTableModel) jTableListaDeUsuarios.getModel();
        model.setNumRows(0);
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[8];
            Usuario aux = lista.get(pos);
            linha[0] = "" + aux.getId();
            linha[1] = aux.getMatriculaCpf();
            linha[2] = aux.getNome().toUpperCase();
            linha[3] = aux.getEmail(); 
            linha[4] = aux.getTelefone();
            linha[5] = "" + aux.getTipoDeUsuario().toString();
            linha[6] = "" + aux.getTipoDeStatus().toString();
            linha[7] = "" + aux.getOab();
            
            model.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaDeUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaDeUsuarios = new javax.swing.JTable();
        jButtonFechar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQtdeRegistros = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();
        jTextFieldDadosApesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Usuários");
        setResizable(false);

        jTableListaDeUsuarios.setAutoCreateRowSorter(true);
        jTableListaDeUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MATRICULA", "NOME", "EMAIL", "TELEFONE", "TIPO USUARIO", "STATUS DO USUÁRIO", "OAB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaDeUsuarios);
        if (jTableListaDeUsuarios.getColumnModel().getColumnCount() > 0) {
            jTableListaDeUsuarios.getColumnModel().getColumn(0).setMinWidth(40);
            jTableListaDeUsuarios.getColumnModel().getColumn(0).setMaxWidth(40);
            jTableListaDeUsuarios.getColumnModel().getColumn(1).setMinWidth(100);
            jTableListaDeUsuarios.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableListaDeUsuarios.getColumnModel().getColumn(4).setMinWidth(120);
            jTableListaDeUsuarios.getColumnModel().getColumn(4).setMaxWidth(120);
            jTableListaDeUsuarios.getColumnModel().getColumn(5).setMinWidth(110);
            jTableListaDeUsuarios.getColumnModel().getColumn(5).setMaxWidth(110);
            jTableListaDeUsuarios.getColumnModel().getColumn(6).setMinWidth(60);
            jTableListaDeUsuarios.getColumnModel().getColumn(6).setMaxWidth(60);
            jTableListaDeUsuarios.getColumnModel().getColumn(7).setMinWidth(60);
            jTableListaDeUsuarios.getColumnModel().getColumn(7).setMaxWidth(60);
        }

        jButtonFechar.setText("FECHAR");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonImprimir.setText("IMPRIMIR");

        jLabel2.setText("Quant. de Registros:");

        jTextFieldQtdeRegistros.setEditable(false);

        jButtonLimpar.setText("LIMPAR");

        javax.swing.GroupLayout jPanelListaDeUsuariosLayout = new javax.swing.GroupLayout(jPanelListaDeUsuarios);
        jPanelListaDeUsuarios.setLayout(jPanelListaDeUsuariosLayout);
        jPanelListaDeUsuariosLayout.setHorizontalGroup(
            jPanelListaDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addGroup(jPanelListaDeUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFechar)
                .addContainerGap())
        );
        jPanelListaDeUsuariosLayout.setVerticalGroup(
            jPanelListaDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaDeUsuariosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanelListaDeUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFechar)
                    .addComponent(jButtonImprimir)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar))
                .addGap(17, 17, 17))
        );

        jTextFieldDadosApesquisar.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDadosApesquisar.setText("Digite aqui o cpf ou nome do usuário");

        jButtonPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelListaDeUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDadosApesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDadosApesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListaDeUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewListaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewListaUsuarios dialog = new ViewListaUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelListaDeUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaDeUsuarios;
    private javax.swing.JTextField jTextFieldDadosApesquisar;
    private javax.swing.JTextField jTextFieldQtdeRegistros;
    // End of variables declaration//GEN-END:variables
}
