/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Editora;
import controle.ControleEditora;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roger
 */
public class ViewListaEditoras extends javax.swing.JDialog {

    ControleEditora controle = null;
    ArrayList<Editora> lista = null;
    
    /**
     * Creates new form ViewListaEditoras
     */
    public ViewListaEditoras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        jTextFieldQtdeRegistros.requestFocus();
        jButtonPesquisarEditora.setEnabled(false);
        
         try{
        controle = new ControleEditora("Editoras.txt");
        imprimirDadosEditoraEmLista(controle.recuperar());
        lista = new ArrayList<>(controle.recuperar());
        jTextFieldQtdeRegistros.setText(""+lista.size());
        
        }catch(Exception erro){
           JOptionPane.showMessageDialog(null,"Ocorreu um erro ao listar as editoras\n" + erro);
        }
    }
    
     private void imprimirDadosEditoraEmLista(ArrayList<Editora> lista) throws Exception {
        DefaultTableModel model = (DefaultTableModel) jTableListaEditoras.getModel();
        model.setNumRows(0);
        Collections.sort(lista);
        for (int pos = 0; pos < lista.size(); pos++) {
            String[] linha = new String[2];
            Editora aux = lista.get(pos);
            linha[0] = "" + aux.getId();
            linha[1] = aux.getDescricaoEditora().toUpperCase();
            model.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelListaEditoras = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaEditoras = new javax.swing.JTable();
        jButtonImprimir = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQtdeRegistros = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();
        jTextFieldDigitarDados = new javax.swing.JTextField();
        jButtonPesquisarEditora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Editoras");

        jTableListaEditoras.setAutoCreateRowSorter(true);
        jTableListaEditoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIÇÃO "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListaEditoras);
        if (jTableListaEditoras.getColumnModel().getColumnCount() > 0) {
            jTableListaEditoras.getColumnModel().getColumn(0).setMinWidth(50);
            jTableListaEditoras.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jButtonImprimir.setText("IMPRIMIR");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });

        jButtonFechar.setText("FECHAR");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel2.setText("Quant. de Registros;");

        jTextFieldQtdeRegistros.setEditable(false);

        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jTextFieldDigitarDados.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldDigitarDados.setText("Digite aqui a descrição da editora");
        jTextFieldDigitarDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDigitarDadosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDigitarDadosFocusLost(evt);
            }
        });

        jButtonPesquisarEditora.setText("Pesquisar");
        jButtonPesquisarEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarEditoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaEditorasLayout = new javax.swing.GroupLayout(jPanelListaEditoras);
        jPanelListaEditoras.setLayout(jPanelListaEditorasLayout);
        jPanelListaEditorasLayout.setHorizontalGroup(
            jPanelListaEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(jPanelListaEditorasLayout.createSequentialGroup()
                .addGroup(jPanelListaEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListaEditorasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFechar))
                    .addGroup(jPanelListaEditorasLayout.createSequentialGroup()
                        .addComponent(jTextFieldDigitarDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisarEditora)))
                .addContainerGap())
        );
        jPanelListaEditorasLayout.setVerticalGroup(
            jPanelListaEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaEditorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListaEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDigitarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarEditora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelListaEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimir)
                    .addComponent(jButtonFechar)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldQtdeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaEditoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListaEditoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        // Aqui uma futura funcionalidade poderá ser implementada
        // conforme solicitação do cliente
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonPesquisarEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarEditoraActionPerformed
        try {
            imprimirDadosEditoraEmLista(controle.pesquisarEditora(jTextFieldDigitarDados.getText()));
            jTextFieldDigitarDados.requestFocus();
            jTextFieldDigitarDados.setText("");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
            jTextFieldDigitarDados.requestFocus();
            jTextFieldDigitarDados.setText("");
        }
    }//GEN-LAST:event_jButtonPesquisarEditoraActionPerformed

    private void jTextFieldDigitarDadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDigitarDadosFocusGained
        if (jTextFieldDigitarDados.getText().equals("Digite aqui a descrição da editora")) {
            jTextFieldDigitarDados.setText("");
            jButtonPesquisarEditora.setEnabled(true);
        }
    }//GEN-LAST:event_jTextFieldDigitarDadosFocusGained

    private void jTextFieldDigitarDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDigitarDadosFocusLost
         if (jTextFieldDigitarDados.getText().equals("")) {
            jTextFieldDigitarDados.setText("Digite aqui a descrição da editora");
            jButtonPesquisarEditora.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldDigitarDadosFocusLost

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        try {
            imprimirDadosEditoraEmLista(controle.recuperar());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewListaEditoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewListaEditoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewListaEditoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewListaEditoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewListaEditoras dialog = new ViewListaEditoras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisarEditora;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelListaEditoras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaEditoras;
    private javax.swing.JTextField jTextFieldDigitarDados;
    private javax.swing.JTextField jTextFieldQtdeRegistros;
    // End of variables declaration//GEN-END:variables
}
